m = int(input('Digite a medida em metros que deseja converter: '))
print('{}M = {}km'.format(m, m/1000))
print('{}M = {}hm'.format(m, m/100))
print('{}M = {}dam'.format(m, m/10))
print('{}M = {}cm'.format(m, m*100))
print('{}M = {}mm'.format(m, m*1000))
